version: 2
jobs:
  dependencies:
    environment:
      - DEPENDENCIES_BASE_URL: "https://raw.githubusercontent.com/wireapp/wire-ios-shared-resources/master"
    macos:
      xcode: "9.0"
    steps:
    - checkout
    - run: |
        curl -O "${DEPENDENCIES_BASE_URL}/environment.sh"
        bash environment.sh
        curl -O "${DEPENDENCIES_BASE_URL}/dependencies.sh"
    - run: bash dependencies.sh

workflows:
  version: 2
  build-and-test:
    jobs:
      - dependencies
