version: 2
jobs:
  dependencies:
    environment:
      - DEPENDENCIES_BASE_URL: "https://raw.githubusercontent.com/wireapp/wire-ios-shared-resources/circle2"
    macos:
      xcode: "9.0"
    steps:
    - checkout
    - restore_cache:
        key: v1-{{ checksum "Cartfile.resolved" }}
    - run: 
        name: "Get dependencies"
        command: |
          curl -O "${DEPENDENCIES_BASE_URL}/dependencies.sh"
          bash dependencies.sh
    - save_cache:
        key: v1-{{ checksum "Cartfile.resolved" }}
        paths: Carthage/Build/iOS
  build:
    environment:
      - DEPENDENCIES_BASE_URL: "https://raw.githubusercontent.com/wireapp/wire-ios-shared-resources/circle2"
    macos:
      xcode: "9.0"
    steps:
    - checkout
    - restore_cache:
        key: v1-{{ checksum "Cartfile.resolved" }}
    - run: 
        name: "Download scripts"
        command: |
          curl -O "${DEPENDENCIES_BASE_URL}/environment.sh"
          bash environment.sh
          curl -O "${DEPENDENCIES_BASE_URL}/build.sh"
    - run: 
        name: "Build"
        command: bash build.sh


workflows:
  version: 2
  build-and-test:
    jobs:
      - dependencies
      - build:
          requires:
            - dependencies
