version: 2
jobs:
  dependencies:
    macos:
      xcode: "9.0.1"
    environment:
      - DEPENDENCIES_BASE_URL: "https://raw.githubusercontent.com/wireapp/wire-ios-shared-resources/master"
    steps:
    - checkout
    - run:
      command: |
        curl -O "${DEPENDENCIES_BASE_URL}/environment.sh"
        bash environment.sh
        curl -O "${DEPENDENCIES_BASE_URL}/dependencies.sh"
    - run:
      command: bash dependencies.sh