
defaults: &defaults
  environment:
    - DEPENDENCIES_BASE_URL: "https://raw.githubusercontent.com/wireapp/wire-ios-shared-resources/circle2"
  macos:
    xcode: "9.0.1"
  shell: /bin/bash --login -eo pipefail

# ----------------CACHING----------------

# Gems
gems_cache: &gems_cache
  key: v3-{{ checksum "Gemfile.lock" }}
  paths: ~/.gem

# Carthage
carthage_cache: &carthage_cache
  key: v2-{{ checksum "Cartfile.resolved" }}
  paths: Carthage/Build

# DerivedData
buildfiles_cache: &buildfiles_cache
  key: v2-{{ .Revision }}
  paths: DerivedData

# ------------Environment-----------------
setup-environment: &setup-environment
  name: "Setup environment"
  command: |
    curl -O "${DEPENDENCIES_BASE_URL}/environment.sh"
    bash environment.sh

version: 2
jobs:
      
  build:
    <<: *defaults
    steps:
    - checkout
    - run: *setup-environment
    - restore_cache: *gems_cache
    - restore_cache: *carthage_cache
    - run: 
        name: "Build"
        command: bash build.sh
    - run: 
        name: "Get dependencies"
        command: bash dependencies.sh
    - save_cache: *buildfiles_cache
    - store_artifacts:
        path: xcode_build.log

  test:
    <<: *defaults
    steps:
    - checkout
    - run: *setup-environment
    - restore_cache: *gems_cache
    - restore_cache: *carthage_cache
    - restore_cache: *buildfiles_cache
    - run: 
        name: "Test"
        command: bash test.sh
    - store_artifacts:
        path: xcode_build.log
    - store_artifacts:
        path: junit/tests.xml


# ----------------WORKFLOWS----------------
workflows:
  version: 2
  build-and-test:
    jobs:
      - build:
      - test:
          requires:
            - build

