version: 2
jobs:
  dependencies:
    macos:
      xcode: "9.0"
    steps:
    - checkout
    - run: |
        curl -O "https://raw.githubusercontent.com/wireapp/wire-ios-shared-resources/master/environment.sh"
        bash environment.sh
        curl -O "https://raw.githubusercontent.com/wireapp/wire-ios-shared-resources/master/dependencies.sh"
    - run: bash dependencies.sh

workflows:
  version: 2
  build-and-test:
    jobs:
      - dependencies
